### ISSUE TITLE
Investigate VPC Endpoints

### ISSUE THREAD

**Issue by dj-maisy** [alphagov/govuk-infrastructure#1426]
## What?
We should explore whether we should be making more use of VPC Endpoints.

### Tasks
- [x] Evaluate costs of current traffic ingress/egress charges against NAT Gateways
- [x] If possible, identify the amount or types of traffic that could be redirected through Endpoints
- [ ] Evaluate the potential savings gained by implementing Endpoints
- [x] Set up VPC Endpoint for ECR (API and DKR)
- [x] ~Set up VPC Endpoint for DocumentDB (used by Licensing)~

## Why?
There are two good reasons to do this:

* The majority of our traffic is currently routed through our NAT Gateways. This is expensive. A lot of our traffic consists of accessing resources and services provided by AWS. If we can route that traffic to use VPC Endpoints, you can avoid paying the premium price for traffic to be processed by the NAT Gateways (by a factor of about 4.8:1)
* Traffic that passes through AWS PrivateLink rather than out of a Nat Gateway (and theoretically via the internet) is inherently more secure, as there is no opportunity for that traffic to leave the AWS ecosystem.

### Considerations
We need to consider (or check) whether we need to do the following things:

* Create or select an existing SG to enable the EKS Nodes to access the VPC Endpoints for the relevant services
* Make sure that route tables are correctly configured to allow the EKS Nodes to access the relevant AWS services via the VPC Endpoints

### Acceptance Criteria

- [x] We've turned this on in Integration (with a feature flag), (we don't have a way to test this anywhere else)
- [ ] We have a document and have demonstrated the value of doing this work. Cost, performance, and implementation will be presented.
- [x] We have a decision on whether this will be promoted to Staging and Production, or it will be rolled back to its previous state in Integration.

**Comment by jasonBirchall** [comment]
[planning] there _should_ be no performance impact

**Comment by dj-maisy** [comment]
### Updates (2025-09-08)

* Enabled VPC Endpoints for ECR and SecretsManager in Integration and Staging

Will now wait for metrics to come through overnight before deciding to enable in Production.

**Comment by dj-maisy** [comment]
### Updates (2025-09-12)

* Enabled VPC Endpoints across all environments for ECR and SecretsManager
* Migrated S3 Gateway Endpoint config from `vpc` to `cluster-infrastructure` Terraform
* Added the S3 Gateway Endpoint Prefix Lists to EKS Private Subnet Route Tables so they actually get used
* [Spreadsheet Tracking VPC Endpoint Costs](https://docs.google.com/spreadsheets/d/1ua99ZN_TV0k-g7VZwHfZ-Rw0GSX-xxCGHRz9CjRAUfU/edit?gid=0#gid=0)
