### ISSUE TITLE
Close down unused Gandi account

### ISSUE THREAD

**Issue by AgaDufrat** [alphagov/govuk-infrastructure#1427]
We’ve consolidated the management of all of our domains into one place: AWS Route53. Gandi no longer serves a purpose.

```[tasklist]
### Tasks
- [x] Raise support request with Gandi https://helpdesk.gandi.net/hc/en-us/requests/188403
- [x] Update any documentation
- [x] Remove login credentials from AWS Secrets Manager - scheduled for deletion
```
