### ISSUE TITLE
Retire govuk-saas-config repo

### ISSUE THREAD

**Issue by AgaDufrat** [alphagov/govuk-infrastructure#1459]
Depends on other items in the task list
Complete Retire a repo steps: https://docs.publishing.service.gov.uk/manual/retiring-a-repo.html

```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/seal/issues/559
- [ ] https://github.com/alphagov/govuk-infrastructure/issues/1405
- [ ] https://github.com/alphagov/govuk-infrastructure/issues/1398
- [x] Complete 'Retire a repo' steps: https://docs.publishing.service.gov.uk/manual/retiring-a-repo.html
```
