### ISSUE TITLE
[EPIC] GOV.UK Running on Graviton

### ISSUE THREAD

**Issue by dj-maisy** [alphagov/govuk-infrastructure#1551]
## What?
This is an "Epic" to make the entirety of GOV.UK run on Graviton and ARM.
```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/govuk-helm-charts/pull/2849
- [ ] https://github.com/alphagov/govuk-helm-charts/issues/2165
- [ ] https://github.com/alphagov/govuk-infrastructure/issues/1402
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1511
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1290
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1285
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1232
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1284
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1262
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1203
- [ ] https://github.com/alphagov/govuk-infrastructure/pull/1251
- [ ] https://github.com/alphagov/govuk-helm-charts/pull/2959
```

Definition of done
---

- [x] All instances are migrated to an Arm architecture.
- [x] Documentation is updated to reflect the change.
- [x] The application developers and any other stakeholders have been informed and are aware of how the change impacts them.
- [ ] The EPIC is demonstrated to the team, showing the process, success criteria, and bumps along the road. This doesn't have to be formal.

**Comment by dj-maisy** [comment]
Done!
